version: '3.8'
services:
  resource_server:
    build: ./src/resource_server
    ports:
      - "${RESOURCE_REST_PORT}:8000"
      - "${RESOURCE_GRPC_PORT}:${RESOURCE_GRPC_PORT}"
    env_file:
      - ./src/.env

  auth_server:
    build: ./auth_server
    ports:
      - "${AUTH_REST_PORT}:8000"
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    env_file:
      - ./src/.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - resource_server
      - auth_server