# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"#\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"A\n\x13VerifyTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.auth.User\"7\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"B\n\x14RefreshTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x18\n\x10new_access_token\x18\x02 \x01(\t2\x98\x01\n\x0b\x41uthService\x12\x42\n\x0bVerifyToken\x12\x18.auth.VerifyTokenRequest\x1a\x19.auth.VerifyTokenResponse\x12\x45\n\x0cRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYTOKENREQUEST']._serialized_start=20
  _globals['_VERIFYTOKENREQUEST']._serialized_end=55
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=57
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=122
  _globals['_USER']._serialized_start=124
  _globals['_USER']._serialized_end=179
  _globals['_REFRESHTOKENREQUEST']._serialized_start=181
  _globals['_REFRESHTOKENREQUEST']._serialized_end=225
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=227
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=293
  _globals['_AUTHSERVICE']._serialized_start=296
  _globals['_AUTHSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
