# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0e\x61uthentication\")\n\x12VerifyTokenRequest\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\"J\n\x13VerifyTokenResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x12\"\n\x04user\x18\x02 \x01(\x0b\x32\x14.authentication.User\"6\n\x04User\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t2^\n\x04\x41uth\x12V\n\x0bVerifyToken\x12\".authentication.VerifyTokenRequest\x1a#.authentication.VerifyTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYTOKENREQUEST']._serialized_start=30
  _globals['_VERIFYTOKENREQUEST']._serialized_end=71
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=73
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=147
  _globals['_USER']._serialized_start=149
  _globals['_USER']._serialized_end=203
  _globals['_AUTH']._serialized_start=205
  _globals['_AUTH']._serialized_end=299
# @@protoc_insertion_point(module_scope)
